### ISSUE TITLE
promptTemplate is not working, accessing modalBox scope and form validation

### ISSUE THREAD

**Issue by Georgi87** [quantumui/quantumui#11]
I want to create a modalBox programatically. The user should enter an amount and a date to do an transaction. As I have to use more than one input I tried to use my own template. However the promptTemplate is not working as the template is not shown, Changing it to contentTemplate works.

Is it possible to pass information to the modalBox scope? E.g. I want to pass the users balance, to check the user doesnt exeed an amount over his limit. Is form validation possible? I imagine the confirm button would have to have the type ng-submit. Can this be changed?

``` javascript
    // sell shares
    $scope.sellSharesModal = function(market, market_hash, outcome, count) {
      $modalBox({
        'title': "Sell shares?",
        'boxType': "confirm",
        'contentTemplate': static_dir + "partials/sell.html",
        'showIcon': false,
        'afterConfirm': function(response) {
          var sell_order = response.sell_order;
        }
      });
    };
```

**Comment by mehmetotkun** [comment]
Thanks for notice. Now, I fixed `promptTemplate` problem, you can download and use it. Also, you can replace just `modalbox.js` if you modified the source code.

Actually, your case come to me a modal issue more than modalbox prompt. However if you want to solve with proptBox you can do something below.

Before start, take care below points about modalBox.
1. `afterConfirm` option and `$confirm` method are only for regular promtbox and confirmbox. 
2. If you want to use `contentTemplate` options within a custom form, You should add custom buttons with events.
   .
   Now, let's try to solve you case by using modalbox.

**First** : Desing your modalbox template like below if you want to use `form`, `ng-form` or `ng-submit`, 

```
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <!--put your form of ng-form here-->
        <form name="sell_order_form" class="modal-content" ng-submit="submitAction(); sell_order_form.$valid && $hide();">
            <div class="modal-header" ng-show="title">
                <h4 class="modal-title" ng-bind="title"></h4>
            </div>
            <div class="modal-body">
                    <div class="modal-body-inner">
                               <!--put your fields here-->
                      </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" ng-click="$hide()">{{closeText}}</button>
                 <!--this is your submit button-->
                <button type="submit" class="btn btn-default" >Submit</button>
            </div>
            <button type="button" class="close" ng-click="$hide()" ng-bind-html="closeIcon">&nbsp;</button>
        </form>
    </div>
</div>
```

In controller;

```

$scope.sellSharesModal = function(market, market_hash, outcome, count) {
      var modalBox = generateModalBox();
     //access modalbox scope and pass parameters;
     var modalBoxScope = modalBox.$scope;
    // do your job;
    };
function generateModalBox() {
   return   $modalBox({
        'title': "Sell shares?",
        'boxType': "custom", //you must set this custom
        'template': static_dir + "partials/sell.html", //use template instead of others
        'showIcon': false,
        'afterCustom': function(modalBoxScope) {
          var sell_order = modalBoxScope.sell_order_form ;
        }
      });
    };
```

Hope can make clear...

**Comment by Georgi87** [comment]
Thank you for your quick and very elaborated answer. I will test this out tomorrow. I remember using a custom template an "OK" button still showed up at the bottom of the modal box. I guess this wont happen using the 'template' option instead of the 'contentTemplate' option?

**Comment by mehmetotkun** [comment]
No. OK button cannot validate your form by itself. However, in above example, the expression on `ng-submit` directive can the same work with 'OK' button. You can use think submit button as 'OK' button.

**Comment by Georgi87** [comment]
Thank you. I tested the code now and it works well. For some reason the 'afterCustom' function was not called after the submit. I solved it adding the submitAction function to the scope of the modal instead.

modalBoxScope.submitAction  = function(modal_scope) {...}

**Comment by mehmetotkun** [comment]
Thanks for notice. Currently, `afterCustom` action only work when content has cunstom buttons inside an element which has `.custom-footer` class. Because, we have analyzed that it is not required when someone use a custom template. You can do your work inside `ng-submit` action if you have custom form. This is the same process.
